### ISSUE TITLE
XSS in CryptDown

### ISSUE THREAD

**Issue by freddyb** [ikkez/CryptDown#2]
STR:
1. Type in the markdown window `<script>alert(1)</script>`
2. Alert comes up :-)

I'd fix this by at best all of the items below:
- disallowing active markup (not that easy when doing yourself, but look at github.com/cure53/DOMPurify for a good third-party solution)
- rendering all markup on a sandbox domain e.g. cryptdownusercontent.com
- applying a strong Content Security Policy. This is considerably easy, when you take into account how small your codebase is.

**Comment by freddyb** [comment]
Note: This is both in editing mode as well as when viewing a saved message.
Example of a stored message: https://cryptdown.eu/view/yb9devlgfh2w (password foo)

**Comment by freddyb** [comment]
Unfortunately, this isn't really complete for two reasons
- markdown allows HTML, this patch just disallows everything.
- The vector `<img src=x onerror=alert(1)>` still triggers XSS if you switch to the preview mode and use the interface to change text using the buttons (e.g. transform some text portion to bold text)

**Comment by Fastidious** [comment]
Agreed with @freddyb.

**Comment by ikkez** [comment]
alright, i moved around some parts. should be better now. thx for the feedback ;)
