### ISSUE TITLE
Error 404!

### ISSUE THREAD

**Issue by ghost** [ikkez/CryptDown#4]
Whenever I create a new paste it leads me to a page that says "Sorry! Error 404, Status: Not Found
HTTP 404 (GET /view/)"

**Comment by ikkez** [comment]
Check your RewriteBase setting in the htaccess file: https://github.com/ikkez/CryptDown/blob/master/.htaccess#L8

**Comment by ghost** [comment]
Thank you but now the save button just loads forever!

**Comment by ikkez** [comment]
revert your changes in `.htaccess` and instead run `/install` to setup the needed sqlite database.
