### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by Fastidious** [ikkez/CryptDown#6]
I don't use Apache, I use Caddy. Is it possible to get rid of `.htaccess`? I don't mind "ugly" URLs, for example. Could a setting be implemented so rewrite isn't needed? Thanks!

**Comment by ikkez** [comment]
I have added a method to disable the normal routing, so you can drop the `.htaccess` if you want. The resulting path becomes like `cryptodown.eu/?r=view/2hexv7ml4q80o`. Go to `config.ini` and turn on the `LEGACY_ROUTING` option for this feature. Don't forget to run install, with `cryptodown.eu/?r=install` on first run. 
Have fun.
